/* SignalOps AI v1.0 — deterministic, browser-only RevOps triage */
(function () {
  'use strict';

  const STORAGE = { rules: 'signalops.rules.v1', meta: 'signalops.rules.meta.v1', runs: 'signalops.runs.v1' };
  const FIELD_ALIASES = {
    account: ['Account Name'], owner: ['Opportunity Owner'], opportunity: ['Opportunity Name'],
    recordType: ['Opportunity Record Type'], dealType: ['Deal Type'], stage: ['Stage'],
    outcome: ['Won /Lost ', 'Won / Lost', 'Won/Lost'], forecast: ['Forecast Category'],
    closeDate: ['Close Date'], closeFY: ['Close FY'], fiscalPeriod: ['Fiscal Period'],
    renewalArr: ['Renewal ARR'], newArr: ['New Committed ARR'], totalBooking: ['Total Booking'],
    weighted: ['Weighted'], probability: ['Probability (%)'], age: ['Age'], recalAge: ['Opp Age Recal'],
    health: ['Health'], licenses: ['Sold Licenses'], utilization: ['Utilization - 1 Month Ago'],
    note: ['CSM Health Note'], gong: ['Latest Gong Call Highlight'], reason: ['At Risk/Churn/Downsell Reason'],
    lossReason: ['Loss Reason'], segment: ['FY26 Segment', 'Segment'], generatedBy: ['Generated by'],
    partner: ['Partner of Record'], industry: ['Industry'], geo: ['Geo'], region: ['Region']
  };
  const REQUIRED = ['Account Name', 'Opportunity Owner', 'Stage', 'Opportunity Record Type'];
  const FIELD_LABELS = {
    utilization: 'Utilization - 1 Month Ago', health: 'Health', note: 'CSM Health Note', gong: 'Latest Gong Call Highlight',
    reason: 'At Risk/Churn/Downsell Reason', renewalArr: 'Renewal ARR', newArr: 'New Committed ARR', stage: 'Stage',
    forecast: 'Forecast Category', outcome: 'Won / Lost', probability: 'Probability (%)', age: 'Age', recalAge: 'Opp Age Recal',
    licenses: 'Sold Licenses', generatedBy: 'Generated by', partner: 'Partner of Record', segment: 'FY26 Segment', dealType: 'Deal Type'
  };

  const DEFAULT_RULES = [
    rule('risk-utilization-critical','Utilization below 33%','risk','utilization','lt','0.33',28,'Low utilization (<33%)','CSM','Launch a 30-day adoption recovery plan with named workflows and weekly usage targets.'),
    rule('risk-health-critical','Critical account health','risk','health','eq','critical',30,'CSM health is Critical','CSM','Escalate to the CSM leader and document an executive save plan within five business days.'),
    rule('risk-health-atrisk','At-risk account health','risk','health','contains','at-risk',18,'CSM health is At-Risk','CSM','Confirm the risk cause, next customer milestone, owner, and date in the renewal plan.'),
    rule('risk-budget-text','Budget or procurement pressure','risk','note','regex','budget|cost|price|procurement|consolidat|cut spend|license count',22,'Budget or procurement pressure in CSM note','AE','Quantify realized value and prepare a right-sized commercial option before procurement controls the timeline.'),
    rule('risk-gong-seat','Seat reduction language','risk','gong','regex','reduce.{0,25}(seat|license)|not.{0,18}using|unused|too many licenses|paying for licenses',24,'Customer language signals downsell risk','AE','Review active-user and license data with the customer; separate adoption recovery from commercial downsell.'),
    rule('risk-reason','Recorded churn/downsell reason','risk','reason','notblank','',25,'Churn or downsell reason is populated','Sales Leader','Validate the reason, assign a save-plan owner, and inspect whether the forecast category reflects the risk.'),
    rule('risk-open-low-forecast','Open renewal still in Pipeline','risk','forecast','eq','pipeline',10,'Open renewal remains Pipeline','AE','Set the next customer commitment and update the forecast category after manager inspection.'),
    rule('exp-utilization','Over-utilization','expansion','utilization','gt','1',30,'Utilization exceeds licensed seats','CSM','Validate sustained over-utilization and introduce an expansion discovery with the AE.'),
    rule('exp-text','Positive expansion language','expansion','note','regex','expand|second site|more sites|rollout|additional team|global|scale',22,'CSM note contains expansion evidence','CSM','Confirm sponsor, use case, deployment timing, and expected seat demand before opening an expansion.'),
    rule('exp-gong','Customer confirms rollout or leadership support','expansion','gong','regex','leadership is bought in|global ops|rollout|next site|more users|expand',20,'Customer call contains expansion evidence','AE','Schedule expansion discovery and size the next use case; do not create pipeline until timing and buyer are confirmed.'),
    rule('exp-healthy','Healthy account','expansion','health','eq','healthy',8,'Account health is Healthy','CSM','Use health as supporting evidence only; confirm usage and a concrete adjacent use case.'),
    rule('risk-zero-license','Utilization recorded with zero licenses','risk','licenses','lte','0',8,'License baseline is missing or zero','RevOps','Resolve the license denominator before using utilization for a commercial decision.')
  ];

  let state = { rows: [], accounts: [], quality: [], fileName: '', fileHash: '', headers: [], runAt: null };
  let rules = loadJson(STORAGE.rules, DEFAULT_RULES);
  let ruleMeta = loadJson(STORAGE.meta, { version: 1, changedAt: null, history: [] });
  let runHistory = loadJson(STORAGE.runs, []);

  function rule(id,name,usecase,field,operator,value,points,label,owner,action) {
    return { id,name,usecase,field,operator,value,points,label,owner,action,active:true,createdAt:'2026-07-19T00:00:00.000Z',updatedAt:'2026-07-19T00:00:00.000Z',reason:'Default rule derived from the supplied Tulip context and data dictionary.' };
  }
  function loadJson(key, fallback) { try { const value = localStorage.getItem(key); return value ? JSON.parse(value) : JSON.parse(JSON.stringify(fallback)); } catch { return JSON.parse(JSON.stringify(fallback)); } }
  function persistRules(change) {
    ruleMeta.version += 1; ruleMeta.changedAt = new Date().toISOString();
    ruleMeta.history.unshift({ version: ruleMeta.version, at: ruleMeta.changedAt, ...change });
    ruleMeta.history = ruleMeta.history.slice(0, 100);
    localStorage.setItem(STORAGE.rules, JSON.stringify(rules)); localStorage.setItem(STORAGE.meta, JSON.stringify(ruleMeta));
  }
  const $ = (id) => document.getElementById(id);
  const money = n => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0,notation:Math.abs(n)>=1e6?'compact':'standard'}).format(Number(n)||0);
  const number = n => new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(Number(n)||0);
  const esc = v => String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const normalize = v => String(v ?? '').trim().toLowerCase();
  const val = (row, key) => { for (const name of FIELD_ALIASES[key] || [key]) if (Object.prototype.hasOwnProperty.call(row,name)) return row[name]; return null; };
  const num = v => { if (v === null || v === undefined || v === '') return null; const n = Number(String(v).replace(/[$,%]/g,'')); return Number.isFinite(n) ? n : null; };
  const combinedText = row => [val(row,'note'),val(row,'gong'),val(row,'reason'),val(row,'lossReason')].filter(Boolean).join(' | ');

  function toast(message) { const el=$('toast'); el.textContent=message; el.classList.add('show'); clearTimeout(toast.t); toast.t=setTimeout(()=>el.classList.remove('show'),2600); }
  function switchView(id) {
    document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));
    document.querySelectorAll('.nav-item').forEach(v=>v.classList.toggle('active',v.dataset.view===id));
    const titles={dashboard:'Renewal command center',accounts:'Account action queue',rules:'Rule memory',quality:'Data quality gate',runs:'Run history',howto:'How to run'};
    $('page-title').textContent=titles[id]; location.hash=id;
  }

  async function handleFile(file) {
    if (!file) return;
    try {
      $('file-badge').textContent='Reading '+file.name+'…';
      const buffer=await file.arrayBuffer(); state.fileHash=await digest(buffer); state.fileName=file.name;
      let rows;
      if (/\.csv$/i.test(file.name)) {
        const text=new TextDecoder().decode(buffer); rows=XLSX.utils.sheet_to_json(XLSX.read(text,{type:'string'}).Sheets.Sheet1,{defval:null,raw:true});
      } else {
        const workbook=XLSX.read(buffer,{type:'array',cellDates:true});
        const sheet=workbook.Sheets[workbook.SheetNames[0]]; rows=XLSX.utils.sheet_to_json(sheet,{defval:null,raw:true});
      }
      if (!rows.length) throw new Error('The first sheet has no data rows.');
      state.headers=Object.keys(rows[0]); state.rows=rows; state.quality=validateData(rows,state.headers);
      const blockers=state.quality.filter(q=>q.severity==='blocker');
      if (blockers.length) { state.accounts=[]; renderAll(); switchView('quality'); throw new Error('Run stopped: '+blockers.length+' blocking schema issue'+(blockers.length===1?'':'s')+'.'); }
      state.accounts=buildAccounts(rows); state.runAt=new Date(); recordRun(); renderAll();
      $('empty-state').classList.add('hidden'); $('dashboard-content').classList.remove('hidden'); $('export-button').disabled=false; $('export-quality').disabled=false;
      $('file-badge').textContent=file.name; switchView('dashboard'); toast('Run complete: '+number(rows.length)+' rows analyzed');
    } catch (error) { $('file-badge').textContent=state.fileName||'No dataset loaded'; toast(error.message||'Could not read this file'); renderQuality(); }
  }
  async function digest(buffer) { try { const hash=await crypto.subtle.digest('SHA-256',buffer); return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('').slice(0,12); } catch { return 'unavailable'; } }

  function validateData(rows, headers) {
    const findings=[];
    const missing=REQUIRED.filter(r=>!headers.includes(r));
    missing.forEach(h=>findings.push(q('blocker','Missing required column: '+h,rows.length,'The scoring and ownership workflow cannot run without this field.','Add the original field to the export; do not rename it.')));
    if (!headers.some(h=>FIELD_ALIASES.outcome.includes(h))) findings.push(q('warning','Outcome column not found',rows.length,'Closed/open outcome checks and historical calibration are unavailable.','Include Won / Lost in the next export.'));
    const tests=[
      ['Invalid outcome value',r=>val(r,'outcome')&&!['won','lost','open'].includes(normalize(val(r,'outcome'))),'Outcome contains a value outside Won, Lost, or Open.','Map invalid values with the Salesforce owner before using outcome metrics.'],
      ['Negative ARR',r=>(num(val(r,'renewalArr'))??0)<0||(num(val(r,'newArr'))??0)<0,'ARR is negative and may represent credits or data-entry defects.','Confirm the commercial meaning; exclude or classify credits explicitly.'],
      ['Utilization outside plausible range',r=>{const u=num(val(r,'utilization'));return u!==null&&(u<0||u>3);},'Utilization is below 0% or above 300%.','Validate active-user and sold-license denominators.'],
      ['Age fields disagree by >30 days',r=>{const a=num(val(r,'age')),b=num(val(r,'recalAge'));return a!==null&&b!==null&&Math.abs(a-b)>30;},'The legacy and recalculated age fields materially disagree.','Use Opp Age Recal for current operations and document the historical break.'],
      ['Partner attribution contradiction',r=>normalize(val(r,'generatedBy'))==='partner'&&!val(r,'partner'),'Generated by says Partner but Partner of Record is blank.','Resolve source attribution before partner performance analysis.'],
      ['Renewal booking mismatch >15%',r=>{if(!normalize(val(r,'dealType')).includes('renewal'))return false;const a=num(val(r,'renewalArr')),b=num(val(r,'totalBooking'));return a>0&&b>0&&Math.abs(a-b)/a>.15;},'Renewal ARR and Total Booking disagree; multi-year structure may explain it but the export does not.','Use Renewal ARR for annual exposure; confirm contract term before TCV conclusions.'],
      ['Open outcome with closed stage',r=>normalize(val(r,'outcome'))==='open'&&/closed won|closed lost|4 renewed|churned/.test(normalize(val(r,'stage'))),'Lifecycle stage and final outcome conflict.','Correct the Salesforce stage or outcome before forecast use.'],
      ['Utilization with missing license baseline',r=>num(val(r,'utilization'))!==null&&!(num(val(r,'licenses'))>0),'Utilization exists but sold licenses is blank or zero.','Repair the denominator; suppress utilization-based action until resolved.'],
      ['Missing both customer text fields',r=>!val(r,'note')&&!val(r,'gong'),'Neither CSM note nor Gong highlight supplies qualitative evidence.','Treat structured-only scores as lower confidence and request an account update.']
    ];
    tests.forEach(([name,test,meaning,action])=>{const count=rows.reduce((n,r)=>n+(test(r)?1:0),0); if(count)findings.push(q(count/rows.length>.2?'warning':'info',name,count,meaning,action));});
    const openRenewals = rows.filter(isCurrentOpenRenewal), accountStates = new Map();
    openRenewals.forEach(r => {
      const name = val(r,'account'); if (!name) return;
      if (!accountStates.has(name)) accountStates.set(name, { health:new Set(), utilization:new Set() });
      const item=accountStates.get(name), health=normalize(val(r,'health')), utilization=num(val(r,'utilization'));
      if(health)item.health.add(health); if(utilization!==null)item.utilization.add(utilization);
    });
    const conflicts=[...accountStates.values()].filter(x=>x.health.size>1||x.utilization.size>1).length;
    if(conflicts)findings.push(q('warning','Conflicting account signals across open renewals',conflicts,'The same account has different health or utilization values across current open renewal opportunities.','Use the most recent account-level source for intervention; do not assume opportunity-row duplication is independent evidence.'));
    if (!missing.length) findings.push(q('info','Required schema present',rows.length,'All minimum columns required to produce the action queue are available.','Proceed; inspect row-level findings before routing actions.'));
    return findings;
  }
  function q(severity,name,count,meaning,action){return{severity,name,count,meaning,action};}

  function conditionMatches(row, r) {
    let actual = r.field==='allText' ? combinedText(row) : val(row,r.field);
    const op=r.operator, expected=r.value;
    if(op==='blank') return actual===null||actual===undefined||String(actual).trim()==='';
    if(op==='notblank') return !(actual===null||actual===undefined||String(actual).trim()==='');
    if(['lt','lte','gt','gte'].includes(op)){const a=num(actual),b=num(expected);if(a===null||b===null)return false;return op==='lt'?a<b:op==='lte'?a<=b:op==='gt'?a>b:a>=b;}
    if(op==='eq') return normalize(actual)===normalize(expected);
    if(op==='neq') return normalize(actual)!==normalize(expected);
    if(op==='contains') return normalize(actual).includes(normalize(expected));
    if(op==='regex') { try{return new RegExp(expected,'i').test(String(actual??''));}catch{return false;} }
    return false;
  }
  function scoreRow(row) {
    const evidence=[]; let risk=0, expansion=0;
    rules.filter(r=>r.active).forEach(r=>{if(conditionMatches(row,r)){const points=Number(r.points)||0;if(r.usecase==='risk')risk+=points;else expansion+=points;evidence.push({ruleId:r.id,usecase:r.usecase,label:r.label,points,owner:r.owner,action:r.action});}});
    const textPresent=Boolean(val(row,'note')||val(row,'gong')); const structuredPresent=val(row,'health')||num(val(row,'utilization'))!==null;
    const confidence=(textPresent&&structuredPresent)?'High':(textPresent||structuredPresent)?'Medium':'Low';
    return {risk:Math.min(risk,100),expansion:Math.min(expansion,100),evidence,confidence};
  }
  function currentFiscalYear(date=new Date()) { return date.getMonth()===0 ? date.getFullYear() : date.getFullYear()+1; }
  function isCurrentOpenRenewal(row) {
    const isOpen=normalize(val(row,'outcome'))==='open';
    const isRenewal=/subscription renewal|renewal/.test(normalize(val(row,'recordType'))+' '+normalize(val(row,'dealType')));
    const closeFY=num(val(row,'closeFY'));
    return isOpen&&isRenewal&&(closeFY===null||closeFY===currentFiscalYear());
  }
  function buildAccounts(rows) {
    const relevant=rows.filter(isCurrentOpenRenewal);
    const map=new Map();
    relevant.forEach((row,index)=>{
      const name=String(val(row,'account')||'Unnamed account'), s=scoreRow(row), renewal=num(val(row,'renewalArr'))||0, newArr=num(val(row,'newArr'))||0;
      if(!map.has(name))map.set(name,{id:slug(name),name,owner:val(row,'owner')||'Unassigned',renewalArr:0,newArr:0,risk:0,expansion:0,evidence:[],rows:[],confidence:'Low',segment:val(row,'segment')||'Unknown',health:val(row,'health')||'Unknown',utilization:num(val(row,'utilization')),closeDate:val(row,'closeDate'),primaryPriority:-1});
      const a=map.get(name);a.renewalArr+=renewal;a.newArr+=newArr;a.rows.push(index+2);
      const rowTier=s.risk>=60?'Critical':s.risk>=40?'High':s.expansion>=35&&s.risk<40?'Expansion':s.risk>=20?'Monitor':'Healthy';
      const rowPriority=({Critical:500,High:400,Expansion:300,Monitor:200,Healthy:100}[rowTier]||0)+s.risk+s.expansion*.3;
      if(rowPriority>a.primaryPriority){
        a.primaryPriority=rowPriority;a.risk=s.risk;a.expansion=s.expansion;a.evidence=s.evidence.map(e=>({...e,opportunity:val(row,'opportunity')}));a.confidence=s.confidence;
        a.health=val(row,'health')||a.health;a.utilization=num(val(row,'utilization'));a.closeDate=val(row,'closeDate')||a.closeDate;a.owner=val(row,'owner')||a.owner;a.segment=val(row,'segment')||a.segment;
      }
    });
    return [...map.values()].map(a=>{
      a.evidence=dedupe(a.evidence,e=>e.ruleId+'|'+e.label);a.tier=tierFor(a);const lead=a.evidence.sort((x,y)=>y.points-x.points)[0];a.action=lead?lead.action:'Monitor through the normal renewal cadence.';a.actionOwner=lead?lead.owner:'CSM';delete a.primaryPriority;return a;
    }).sort((a,b)=>priority(b)-priority(a)||b.renewalArr-a.renewalArr);
  }
  function dedupe(items,key){const seen=new Set();return items.filter(x=>{const k=key(x);if(seen.has(k))return false;seen.add(k);return true;});}
  function tierFor(a){if(a.risk>=60)return'Critical';if(a.risk>=40)return'High';if(a.expansion>=35&&a.risk<40)return'Expansion';if(a.risk>=20)return'Monitor';return'Healthy';}
  function priority(a){return({Critical:500,High:400,Expansion:300,Monitor:200,Healthy:100}[a.tier]||0)+a.risk+a.expansion*.3;}
  function slug(v){return normalize(v).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,70);}

  function recordRun(){
    const counts=countTiers(); const run={id:Date.now(),at:state.runAt.toISOString(),fileName:state.fileName,fileHash:state.fileHash,rows:state.rows.length,accounts:state.accounts.length,ruleVersion:ruleMeta.version,quality:state.quality.reduce((n,q)=>n+q.count,0),critical:counts.Critical||0,high:counts.High||0,expansion:counts.Expansion||0};
    runHistory.unshift(run);runHistory=runHistory.slice(0,30);localStorage.setItem(STORAGE.runs,JSON.stringify(runHistory));
  }
  function countTiers(){return state.accounts.reduce((o,a)=>(o[a.tier]=(o[a.tier]||0)+1,o),{});}
  function arrByTier(tier){return state.accounts.filter(a=>a.tier===tier).reduce((s,a)=>s+a.renewalArr,0);}

  function renderAll(){renderDashboard();renderAccounts();renderRules();renderQuality();renderRuns();}
  function renderDashboard(){
    if(!state.accounts.length)return; const counts=countTiers();
    $('run-banner').innerHTML=`Run <strong>${esc(state.fileHash)}</strong> completed with rule set <strong>v${ruleMeta.version}</strong>. ${number(state.rows.length)} rows → ${number(state.accounts.length)} renewal/expansion accounts. Same file + same rule version = same queue.`;
    $('critical-arr').textContent=money(arrByTier('Critical'));$('critical-count').textContent=(counts.Critical||0)+' accounts';
    $('risk-arr').textContent=money(arrByTier('High')+arrByTier('Monitor'));$('risk-count').textContent=((counts.High||0)+(counts.Monitor||0))+' accounts';
    $('expansion-arr').textContent=money(arrByTier('Expansion'));$('expansion-count').textContent=(counts.Expansion||0)+' accounts';
    const warningRows=state.quality.filter(q=>q.severity!=='info').reduce((s,q)=>s+q.count,0), confidence=Math.max(0,100-Math.round(warningRows/Math.max(state.rows.length,1)*35));
    $('confidence').textContent=confidence+'%';$('quality-count').textContent=number(warningRows)+' warning instances';
    $('top-accounts').innerHTML=state.accounts.filter(a=>a.tier!=='Healthy').slice(0,8).map(a=>`<div class="account-row"><span class="risk-pip ${a.tier.toLowerCase()}"></span><div><strong>${esc(a.name)}</strong><small>${esc(a.owner)} · ${esc(a.evidence[0]?.label||'No triggered rule')}</small></div><span class="arr">${money(a.renewalArr)}<small>${a.tier} · ${a.risk||a.expansion}</small></span></div>`).join('')||'<p class="muted">No prioritized accounts.</p>';
    const tiers=['Critical','High','Monitor','Expansion','Healthy'],max=Math.max(...tiers.map(arrByTier),1),colors={Critical:'#b43d3d',High:'#d28417',Monitor:'#64819e',Expansion:'#1c8a6b',Healthy:'#91a49c'};
    $('tier-chart').innerHTML=tiers.map(t=>`<div class="bar-row"><span>${t}</span><div class="bar-track"><div class="bar-fill" style="width:${arrByTier(t)/max*100}%;background:${colors[t]}"></div></div><b>${money(arrByTier(t))}</b></div>`).join('');
    const signals={};state.accounts.forEach(a=>a.evidence.forEach(e=>signals[e.label]=(signals[e.label]||0)+1));const list=Object.entries(signals).sort((a,b)=>b[1]-a[1]).slice(0,6),m=Math.max(...list.map(x=>x[1]),1);
    $('signal-chart').innerHTML=list.map(([label,count])=>`<div class="signal-row"><span>${esc(label)}</span><b>${count}</b><div class="bar-track"><div class="bar-fill" style="width:${count/m*100}%;background:#1c8a6b"></div></div></div>`).join('')||'<p class="muted">No signals triggered.</p>';
  }
  function renderAccounts(){
    const owners=[...new Set(state.accounts.map(a=>a.owner))].sort();const select=$('owner-filter'),current=select.value;select.innerHTML='<option value="all">All owners</option>'+owners.map(o=>`<option>${esc(o)}</option>`).join('');select.value=owners.includes(current)?current:'all';filterAccounts();
  }
  function filterAccounts(){
    const search=normalize($('account-search').value),tier=$('tier-filter').value,owner=$('owner-filter').value;
    const list=state.accounts.filter(a=>(tier==='all'||a.tier===tier)&&(owner==='all'||a.owner===owner)&&(!search||normalize(a.name+' '+a.owner+' '+a.evidence.map(e=>e.label).join(' ')).includes(search)));
    $('queue-count').textContent=number(list.length)+' accounts';
    $('accounts-body').innerHTML=list.map(a=>`<tr><td><span class="tier ${a.tier}">${a.tier}</span></td><td><strong>${esc(a.name)}</strong><br><small class="muted">${esc(a.segment)} · ${esc(a.confidence)} confidence</small></td><td>${esc(a.owner)}</td><td>${money(a.renewalArr)}</td><td><strong>${a.tier==='Expansion'?a.expansion:a.risk}</strong><br><small class="muted">risk ${a.risk} / expand ${a.expansion}</small></td><td class="evidence">${esc(a.evidence.slice(0,2).map(e=>e.label).join(' · ')||'No triggered rule')}</td><td class="evidence"><strong>${esc(a.actionOwner)}:</strong> ${esc(a.action)}</td><td><button class="row-action" data-account="${esc(a.id)}">Inspect →</button></td></tr>`).join('')||'<tr><td colspan="8" class="muted">Upload a dataset or change the filters.</td></tr>';
  }
  function renderRules(){
    $('active-rule-count').textContent=rules.filter(r=>r.active).length;$('rule-version').textContent='v'+ruleMeta.version;$('last-rule-change').textContent=ruleMeta.changedAt?new Date(ruleMeta.changedAt).toLocaleDateString():'Default';
    $('rule-list').innerHTML=rules.map(r=>`<article class="rule-card ${r.active?'':'inactive'}"><span class="rule-usecase ${r.usecase}">${r.usecase==='risk'?'↓':'↑'}</span><div><h3>${esc(r.name)}</h3><p>${esc(FIELD_LABELS[r.field]||r.field)} ${esc(operatorLabel(r.operator))} ${esc(r.value)} · ${r.points} points · owner ${esc(r.owner)}</p><div class="rule-meta"><span class="chip">${r.active?'Active':'Inactive'}</span><span class="chip">${esc(r.label)}</span></div></div><div class="rule-actions"><button class="icon-button" title="Edit" data-edit-rule="${esc(r.id)}">✎</button><button class="icon-button" title="Toggle" data-toggle-rule="${esc(r.id)}">${r.active?'◉':'○'}</button><button class="icon-button" title="Delete" data-delete-rule="${esc(r.id)}">×</button></div></article>`).join('');
  }
  function operatorLabel(op){return({lt:'<',lte:'≤',gt:'>',gte:'≥',eq:'equals',neq:'does not equal',contains:'contains',regex:'matches',blank:'is blank',notblank:'is not blank'}[op]||op);}
  function renderQuality(){
    const counts={blocker:0,warning:0,info:0};state.quality.forEach(q=>counts[q.severity]+=q.count);
    $('quality-summary').innerHTML=['blocker','warning','info'].map(s=>`<div class="quality-card ${s}"><strong>${number(counts[s])}</strong><span>${s==='blocker'?'blocking instances':s==='warning'?'warning instances':'information instances'}</span></div>`).join('');
    $('quality-body').innerHTML=state.quality.map(q=>`<tr><td><span class="severity ${q.severity}">${q.severity}</span></td><td><strong>${esc(q.name)}</strong></td><td>${number(q.count)}</td><td>${esc(q.meaning)}</td><td>${esc(q.action)}</td></tr>`).join('')||'<tr><td colspan="5" class="muted">Upload a dataset to run validation.</td></tr>';
  }
  function renderRuns(){
    $('run-list').innerHTML=runHistory.map(r=>`<article class="run-card"><div><h3>${esc(r.fileName)}</h3><small>${new Date(r.at).toLocaleString()} · hash ${esc(r.fileHash)}</small></div><div class="run-stat"><span>Rows</span><strong>${number(r.rows)}</strong></div><div class="run-stat"><span>Rules</span><strong>v${r.ruleVersion}</strong></div><div class="run-stat"><span>Critical / high</span><strong>${r.critical} / ${r.high}</strong></div><div class="run-stat"><span>Expansion</span><strong>${r.expansion}</strong></div></article>`).join('')||'<div class="empty-state"><h2>No completed runs yet.</h2><p>Upload the supplied workbook to create the first audit entry.</p></div>';
  }

  function showAccount(id){
    const a=state.accounts.find(x=>x.id===id);if(!a)return;
    $('account-detail').innerHTML=`<div class="account-detail"><button class="icon-button close-detail" onclick="document.getElementById('account-dialog').close()">×</button><div class="detail-head"><div><p class="eyebrow">ACCOUNT EVIDENCE PACK</p><h2>${esc(a.name)}</h2><span class="tier ${a.tier}">${a.tier}</span></div><div><strong>${money(a.renewalArr)}</strong><br><small class="muted">renewal ARR</small></div></div><div class="detail-grid"><div class="detail-block"><h3>Decision record</h3><p><b>Owner:</b> ${esc(a.owner)}</p><p><b>Action owner:</b> ${esc(a.actionOwner)}</p><p><b>Risk / expansion:</b> ${a.risk} / ${a.expansion}</p><p><b>Confidence:</b> ${esc(a.confidence)}</p><p><b>Source rows:</b> ${a.rows.join(', ')}</p></div><div class="detail-block"><h3>Recommended intervention</h3><p>${esc(a.action)}</p><p class="muted">Human review required before forecast override or customer outreach.</p></div><div class="detail-block full"><h3>Triggered evidence</h3><div class="evidence-list">${a.evidence.map(e=>`<div class="evidence-item"><b>${esc(e.label)} · ${e.points} pts</b><span>${esc(e.usecase)} · ${esc(e.owner)} · ${esc(e.opportunity||'Account evidence')}</span></div>`).join('')||'<span class="muted">No rule evidence.</span>'}</div></div></div></div>`;
    $('account-dialog').showModal();
  }

  function populateRuleForm(r){
    $('rule-id').value=r?.id||'';$('rule-name').value=r?.name||'';$('rule-usecase').value=r?.usecase||'risk';$('rule-field').value=r?.field||'utilization';$('rule-operator').value=r?.operator||'lt';$('rule-value').value=r?.value||'';$('rule-points').value=r?.points||20;$('rule-owner').value=r?.owner||'CSM';$('rule-label').value=r?.label||'';$('rule-action').value=r?.action||'';$('rule-reason').value='';$('rule-active').checked=r?.active??true;$('rule-dialog-title').textContent=r?'Edit rule':'Create rule';$('rule-dialog').showModal();
  }
  function saveRule(){
    const id=$('rule-id').value||('rule-'+Date.now()),existing=rules.find(r=>r.id===id),now=new Date().toISOString();
    const item={id,name:$('rule-name').value.trim(),usecase:$('rule-usecase').value,field:$('rule-field').value,operator:$('rule-operator').value,value:$('rule-value').value.trim(),points:Number($('rule-points').value),owner:$('rule-owner').value,label:$('rule-label').value.trim(),action:$('rule-action').value.trim(),reason:$('rule-reason').value.trim(),active:$('rule-active').checked,createdAt:existing?.createdAt||now,updatedAt:now};
    if(item.operator==='regex'){try{new RegExp(item.value)}catch{toast('The regular expression is invalid');return false;}}
    if(existing)rules[rules.indexOf(existing)]=item;else rules.push(item);persistRules({action:existing?'updated':'created',ruleId:id,name:item.name,reason:item.reason});
    rerunWithRules();renderRules();toast('Rule saved as version '+ruleMeta.version);return true;
  }
  function rerunWithRules(){if(!state.rows.length)return;state.accounts=buildAccounts(state.rows);renderDashboard();renderAccounts();}
  function toggleRule(id){const r=rules.find(x=>x.id===id);if(!r)return;r.active=!r.active;r.updatedAt=new Date().toISOString();persistRules({action:r.active?'activated':'deactivated',ruleId:id,name:r.name,reason:'Status changed in Rule Memory.'});rerunWithRules();renderRules();toast(r.name+' '+(r.active?'activated':'deactivated'));}
  function deleteRule(id){const r=rules.find(x=>x.id===id);if(!r||!confirm('Delete “'+r.name+'”? The audit history will retain the deletion event.'))return;rules=rules.filter(x=>x.id!==id);persistRules({action:'deleted',ruleId:id,name:r.name,reason:'Deleted in Rule Memory.'});rerunWithRules();renderRules();toast('Rule deleted');}

  function download(name,content,type='text/csv;charset=utf-8'){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),500);}
  function csv(rows){if(!rows.length)return'';const heads=Object.keys(rows[0]);const cell=v=>'"'+String(v??'').replace(/"/g,'""')+'"';return heads.map(cell).join(',')+'\n'+rows.map(r=>heads.map(h=>cell(r[h])).join(',')).join('\n');}
  function exportQueue(){download('signalops-weekly-queue-'+new Date().toISOString().slice(0,10)+'.csv',csv(state.accounts.map((a,i)=>({priority:i+1,tier:a.tier,account:a.name,opportunity_owner:a.owner,action_owner:a.actionOwner,renewal_arr:a.renewalArr,new_arr:a.newArr,risk_score:a.risk,expansion_score:a.expansion,confidence:a.confidence,health:a.health,utilization:a.utilization,evidence:a.evidence.map(e=>e.label).join(' | '),recommended_action:a.action,rule_version:ruleMeta.version,input_hash:state.fileHash}))));}
  function exportQuality(){download('signalops-data-quality-'+new Date().toISOString().slice(0,10)+'.csv',csv(state.quality));}
  function exportRules(){download('signalops-rule-pack-v'+ruleMeta.version+'.json',JSON.stringify({product:'SignalOps AI',schemaVersion:1,exportedAt:new Date().toISOString(),meta:ruleMeta,rules},null,2),'application/json');}
  async function importRules(file){try{const data=JSON.parse(await file.text());if(!Array.isArray(data.rules)||!data.rules.every(r=>r.id&&r.name&&r.field&&r.operator))throw new Error('Not a valid SignalOps rule pack.');rules=data.rules;persistRules({action:'imported',ruleId:'rule-pack',name:file.name,reason:'Imported rule pack after schema validation.'});rerunWithRules();renderRules();toast('Imported '+rules.length+' rules');}catch(e){toast(e.message);}}

  function bind(){
    document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
    document.querySelectorAll('[data-jump]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.jump)));
    $('file-input').addEventListener('change',e=>handleFile(e.target.files[0]));$('export-button').addEventListener('click',exportQueue);$('export-quality').addEventListener('click',exportQuality);
    $('account-search').addEventListener('input',filterAccounts);$('tier-filter').addEventListener('change',filterAccounts);$('owner-filter').addEventListener('change',filterAccounts);
    $('accounts-body').addEventListener('click',e=>{const b=e.target.closest('[data-account]');if(b)showAccount(b.dataset.account);});
    $('new-rule').addEventListener('click',()=>populateRuleForm());$('close-dialog').addEventListener('click',()=>$('rule-dialog').close());$('cancel-dialog').addEventListener('click',()=>$('rule-dialog').close());
    $('rule-form').addEventListener('submit',e=>{e.preventDefault();if(saveRule())$('rule-dialog').close();});
    $('rule-list').addEventListener('click',e=>{let b=e.target.closest('[data-edit-rule],[data-toggle-rule],[data-delete-rule]');if(!b)return;if(b.dataset.editRule)populateRuleForm(rules.find(r=>r.id===b.dataset.editRule));if(b.dataset.toggleRule)toggleRule(b.dataset.toggleRule);if(b.dataset.deleteRule)deleteRule(b.dataset.deleteRule);});
    $('export-rules').addEventListener('click',exportRules);$('import-rules').addEventListener('click',()=>$('rules-input').click());$('rules-input').addEventListener('change',e=>importRules(e.target.files[0]));
    $('clear-runs').addEventListener('click',()=>{if(confirm('Clear the local run audit history?')){runHistory=[];localStorage.setItem(STORAGE.runs,'[]');renderRuns();}});
    $('rule-field').innerHTML=Object.entries(FIELD_LABELS).map(([k,v])=>`<option value="${k}">${esc(v)}</option>`).join('')+'<option value="allText">All customer text</option>';
    const initial=location.hash.slice(1);if(document.getElementById(initial)?.classList.contains('view'))switchView(initial);
  }

  globalThis.SignalOpsCore = {
    analyze(rows) {
      const headers = rows.length ? Object.keys(rows[0]) : [];
      const quality = validateData(rows, headers);
      const blockers = quality.filter(item => item.severity === 'blocker');
      return { headers, quality, blockers, accounts: blockers.length ? [] : buildAccounts(rows), ruleVersion: ruleMeta.version };
    },
    getRules: () => JSON.parse(JSON.stringify(rules)),
    setRules(nextRules) { rules = JSON.parse(JSON.stringify(nextRules)); },
    defaults: JSON.parse(JSON.stringify(DEFAULT_RULES))
  };
  if (typeof document !== 'undefined') { bind(); renderAll(); }
})();
